//
//  print_metadata.h
//  kcc2
//
//  Created by Christophe Bronner on 2024-07-27.
//

#include <kcc/print.h>

char *ast_nameof(enum ast_kind kind) {
	static char *names[AST_MAX] = {
		// Translation Unit
		[N_UNIT] = "unit",
		// Common
		[N_IDENTIFIER] = "identifier",
		// Literals
		[N_INTEGER_LITERAL] = "literal",
		// Declarations
		[N_DECLARATION] = "declaration",
		[N_DECLARATOR] = "declarator",
		[N_POINTER_DECLARATOR] = "*",
		[N_GROUP_DECLARATOR] = "group",
		[N_IDENTIFIER_DECLARATOR] = "identifier",
		[N_ARRAY_DECLARATOR] = "[]",
		[N_FUNCTION_DECLARATOR] = "function",
		// Expressions
		[N_ADD] = "+",
		[N_MULTIPLY] = "*",
		[N_CAST] = "cast",
	};
	return names[kind];
}

char *token_nameof(enum token_kind kind) {
	static char *names[TOKEN_MAX] = {
		[T_UNKNOWN] = "unknown",
		[T_EOF] = "eof",
		[T_WHITESPACE] = "whitespace",
		[T_NEWLINE] = "newline",
		[T_COMMENT] = "comment",
		[T_DOCUMENTATION] = "documentation",
		[TL_STRING] = "string literal",
		[TL_CHAR] = "char literal",
		[TL_CHARS] = "chars literal",
		[TL_FLOAT] = "float literal",
		[T_INTEGER_LITERAL] = "integer literal",
		[TM_UTF8] = "utf8",
		[TM_UTF16] = "utf16",
		[TM_UTF32] = "utf32",
		[TM_WIDE] = "wide",
		[TM_FLOAT] = "f",
		[TM_DOUBLE] = "d",
		[TM_LDOUBLE] = "l",
		[TM_DECIMAL32] = "df",
		[TM_DECIMAL64] = "dd",
		[TM_DECIMAL128] = "dl",
		[TM_UNSIGNED] = "u",
		[TM_LONG] = "l",
		[TM_LONGLONG] = "ll",
		[TM_BITINT] = "wb",
		[T_IDENTIFIER] = "identifier",
		[T_LPAREN] = "(",
		[T_RPAREN] = ")",
		[T_LBRACKET] = "[",
		[T_RBRACKET] = "]",
		[T_LCURLY] = "{",
		[T_RCURLY] = "}",
		[T_SEMICOLON] = ";",
		[T_COLON] = ":",
		[T_COMMA] = ",",
		[T_ADD] = "+",
		[T_INCREMENT] = "++",
		[T_SUBTRACT] = "-",
		[T_DECREMENT] = "--",
		[T_ASTERISK] = "*",
		[T_DIVIDE] = "/",
		[T_PERCENT] = "%",
		[T_TILDE] = "~",
		[T_EXCLAIM] = "!",
		[T_QUESTION] = "?",
		[T_EQ] = "==",
		[T_NEQ] = "!=",
		[T_GT] = ">",
		[T_GTE] = ">=",
		[T_LT] = "<",
		[T_LTE] = "<=",
		[T_AMPERSAND] = "&",
		[T_PIPE] = "|",
		[T_OR] = "||",
		[T_CARET] = "^",
		[T_AND] = "&&",
		[T_ACCESS] = ".",
		[T_INDIRECT_ACCESS] = "->",
		[T_LSHIFT] = "<<",
		[T_RSHIFT] = ">>",
		[T_ASSIGN] = "=",
		[T_ASSIGN_MULTIPLY] = "*=",
		[T_ASSIGN_DIVIDE] = "/=",
		[T_ASSIGN_MODULO] = "%=",
		[T_ASSIGN_ADD] = "+=",
		[T_ASSIGN_SUBTRACT] = "-=",
		[T_ASSIGN_LSHIFT] = "<<=",
		[T_ASSIGN_RSHIFT] = ">>=",
		[T_ASSIGN_BITWISE_AND] = "&=",
		[T_ASSIGN_BITWISE_XOR] = "^=",
		[T_ASSIGN_BITWISE_OR] = "|=",
		[T_ALIGNAS] = "alignas",
		[T_ALIGNOF] = "alignof",
		[T_AUTO] = "auto",
		[T_BITINT] = "_BitInt",
		[T_BOOL] = "bool",
		[T_CHAR] = "char",
		[T_COMPLEX] = "_Complex",
		[T_CONST] = "const",
		[T_DECIMAL32] = "_Decimal32",
		[T_DECIMAL64] = "_Decimal64",
		[T_DECIMAL128] = "_Decimal128",
		[T_DEFAULT] = "default",
		[T_DOUBLE] = "double",
		[T_ELSE] = "else",
		[T_FLOAT] = "float",
		[T_FOR] = "for",
		[T_GENERIC] = "_Generic",
		[T_IF] = "if",
		[T_INT] = "int",
		[T_LONG] = "long",
		[T_RETURN] = "return",
		[T_SHORT] = "short",
		[T_SIGNED] = "signed",
		[T_SIZEOF] = "sizeof",
		[T_UNSIGNED] = "unsigned",
		[T_VOID] = "void",
		[T_WHILE] = "while",
		[T_DIRECTIVE] = "#",
		[T_IFDEF] = "ifdef",
		[T_IFNDEF] = "ifndef",
		[T_ELIF] = "elif",
		[T_ELIFDEF] = "elifdef",
		[T_ELIFNDEF] = "elifndef",
		[T_ENDIF] = "endif",
		[T_INCLUDE] = "include",
		[T_EMBED] = "embed",
		[T_DEFINE] = "define",
		[T_UNDEF] = "undef",
		[T_LINE] = "line",
		[T_ERROR] = "error",
		[T_WARNING] = "warning",
		[T_PRAGMA] = "pragma",
	};
	return names[kind];
}
