//
//  precedence.h
//  kcc2
//
//  Created by Christophe Bronner on 2024-11-13.
//

#pragma once

enum precedence {
	PRECEDENCE_NONE,
	PRECEDENCE_COMMA,
	PRECEDENCE_ASSIGNMENT,
	PRECEDENCE_CONDITIONAL,
	PRECEDENCE_LOGICAL_OR,
	PRECEDENCE_LOGICAL_AND,
	PRECEDENCE_BITWISE_OR,
	PRECEDENCE_BITWISE_XOR,
	PRECEDENCE_BITWISE_AND,
	PRECEDENCE_EQUALITY,
	PRECEDENCE_RELATIONAL,
	PRECEDENCE_SHIFT,
	PRECEDENCE_ADDITIVE,
	PRECEDENCE_MULTIPLICATIVE,
	PRECEDENCE_CAST,
	PRECEDENCE_COUNT,
};
